# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Rebulkan_config = debug

else ifeq ($(config),release)
  Rebulkan_config = release

else ifeq ($(config),dist)
  Rebulkan_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Rebulkan

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Rebulkan:
ifneq (,$(Rebulkan_config))
	@echo "==== Building Rebulkan ($(Rebulkan_config)) ===="
	@${MAKE} --no-print-directory -C . -f Rebulkan.make config=$(Rebulkan_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Rebulkan.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Rebulkan"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"