include(FetchContent)

include(deps/FetchVolk)
include(deps/FetchFMT)
include(deps/FetchSTB)
include(deps/FetchGLFW)
include(deps/FetchMiniAudio)
include(deps/FetchGLM)
include(deps/FetchFreeType)
include(deps/FetchNlohmannJson)
include(deps/FetchAssimp)
include(deps/FetchSQlite)
include(deps/FetchLua)
include(deps/FetchKTX)