include(FetchContent)

set(ASSIMP_TAG v5.4.3)
set(FREETYPE_TAG VER-2-13-3)
set(FMT_TAG 11.2.0)
set(GLFW_TAG 3.4)
set(GLM_TAG 1.0.1)
set(KTX_TAG main)
set(LUA_TAG v5.4.7)
set(MINIAUDIO_TAG  0.11.22)
set(NH_JSON_TAG v3.12.0)
set(STB_TAG master)
set(SQLITE_TAG version-3.49.2)
set(VOLK_TAG 1.4.304)

set(FETCH_GIT_SHALLOW TRUE)
set(FETCH_GIT_PROGRESS TRUE)
set(FETCH_UPDATE_DISCONNECTED TRUE)

include(deps/FetchAssimp)
include(deps/FetchFreeType)
include(deps/FetchGLFW)
include(deps/FetchGLM)
include(deps/FetchFMT)
include(deps/FetchKTX)
include(deps/FetchLua)
include(deps/FetchMiniAudio)
include(deps/FetchNlohmannJson)
include(deps/FetchSTB)
include(deps/FetchSQlite)
include(deps/FetchVolk)
