set(CMAKE_SYSTEM_NAME Windows)

if(NOT DEFINED CMAKE_SYSROOT)
  set(CMAKE_SYSROOT "G:/llvm-mingw")
  message(STATUS "CMAKE_SYSROOT not defined, defaulting to ${CMAKE_SYSROOT}")
endif()

set(CMAKE_C_COMPILER   "${CMAKE_SYSROOT}/bin/clang.exe")
set(CMAKE_CXX_COMPILER "${CMAKE_SYSROOT}/bin/clang++.exe")
set(CMAKE_RC_COMPILER  "${CMAKE_SYSROOT}/bin/windres.exe")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES "")
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES "")
