name: CMake

on:
  push:
    branches: [ "tooling" ]
  pull_request:
    branches: [ "tooling" ]    
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VULKAN_SDK_ACTIONS: external/Vulkan-Headers/include
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        name: KhronosGroup/Vulkan-Headers
        repository: KhronosGroup/Vulkan-Headers
        path: external
        cache: true
        
    - uses: actions/checkout@v3
      with:
        path: main

    - name: Install dependancies
      run: sudo apt-get install xorg-dev libglu1-mesa-dev
      
    - name: ls 
      run: ls -l
      
    - name: move to main
      run: cd main

    - name: ls 
      run: ls -l
      
    - name: chmod x rbkBuild 
      run:  chmod +x ./bin/rbkBuild.sh
      
    - name: Configure CMake
      run: ./bin/rbkBuild.sh -lfalse

    - name: Build
      run: ./bin/rbkBuild.sh -i 

