name: CMake

on:
  push:
    branches: [ "tooling" ]
  pull_request:
    branches: [ "tooling" ]    
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VULKAN_SDK_ACTIONS: vendor/KhronosGroup/Vulkan-Headers/include
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        repository: KhronosGroup/Vulkan-Headers
        path: vendor
        
    - uses: actions/checkout@v3

    - name: Install dependancies
      run: sudo apt-get install xorg-dev libglu1-mesa-dev libvulkan1 mesa-vulkan-drivers
      
    - name: chmod x rbkBuild 
      run:  chmod +x ./bin/rbkBuild.sh
      
    - name: Configure CMake
      run: ./bin/rbkBuild.sh -lfalse

    - name: Build
      run: ./bin/rbkBuild.sh -i 

