name: CMake

on:
  push:
    branches: [ "tooling" ]
  pull_request:
    branches: [ "tooling" ]    
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@master
      with:
        name: KhronosGroup/Vulkan-Headers
        cache: true
        
    - name: Set VULKAN_SDK
      run: export VULKAN_SDK=./KhronosGroup/Vulkan-Headers/include
      
    - uses: actions/checkout@v3

    - name: chmod x rbkBuild 
      run:  chmod +x ./bin/rbkBuild.sh
      
    - name: Configure CMake
      run: ./bin/rbkBuild.sh -lfalse

    - name: Build
      run: ./bin/rbkBuild.sh -i 

