name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        repository: KhronosGroup/Vulkan-Headers
        path: external
        cache: true
        
    - uses: actions/checkout@v3
      with:
        path: main

    - name: Install dependancies
      run: sudo apt-get update && sudo apt-get install xorg-dev libglu1-mesa-dev libvulkan1 mesa-vulkan-drivers ninja-build

    - name: Set env variable VULKAN_SDK_ACTIONS
      run: echo "VULKAN_SDK_ACTIONS=${{ github.workspace }}/external/include" >> $GITHUB_ENV
    
    - name: Configure && Build
      run: |
        cd main
        chmod +x ./bin/plpBuild.sh
        ./bin/plpBuild.sh -l true
        ./bin/plpBuild.sh -i 
